services:
  db:
    container_name: file-storage-database
    image: postgres:18.6
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d dev_db" ]
      interval: 3s
      timeout: 3s
      retries: 20

  web:
    container_name: file-storage-django
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app/:/app/
      - /app/.venv
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  s3mock:
    container_name: file-storage-s3mock
    image: adobe/s3mock:latest
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=filebucket
    ports:
      - 9090:9090
      - 9191:9191

volumes:
  postgres_data:
