[project]
name = "file-storage"
version = "0.1.0"
description = "File storage app"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.88",
    "django>=6.1.1",
    "django-storages[s3]>=1.14.6",
    "djangorestframework>=3.18.0",
    "markdown>=3.10.3",
    "pre-commit>=4.6.2",
    "psycopg[binary]>=3.3.5",
]

[tool.uv]
package = false
exclude-newer = "7 days"
